version: '3'
services:
  prod:
    build:
      context: .
      dockerfile: Dockerfile-debian
      args:
          BOKEH_VERSION: 0.13.0
          TORNADO_VERSION: 6.0.3
    image: "mint-project/viz_bokeh:latest"
    ports:
      - 9099:5006
  gams:
    build:
      context: .
      dockerfile: Dockerfile-gams
    image: "mint-project/viz_bokeh:gams"
    ports:
      - 9098:5006      