version: '3'
services:
  gams:
    build:
      context: .
      dockerfile: Dockerfile-base
    image: "mint-project/viz_bokeh:gams"  
  prod:
    build:
      context: .
      dockerfile: Dockerfile
    image: "mint-project/viz_bokeh:latest"
    depends_on:
      - gams
    ports:
      - 9099:5006
