version: '3'
services:
  economic:
    build:
      context: .
      dockerfile: Dockerfile
    image: "mint-project/viz_bokeh:economic"
    ports:
      - 9099:5006
  common:
    build:
      context: .
      dockerfile: Dockerfile-base
      args:
          BOKEH_VERSION: 0.13.0
          TORNADO_VERSION: 6.0.3
    image: "mint-project/viz_bokeh:latest"