#/* vim: set filetype=dockerfile : */
FROM mint-project/viz_bokeh:gams

RUN mkdir /bokeh
WORKDIR /bokeh
COPY ./requirements.txt .
RUN pip install -r requirements.txt
COPY . /bokeh

ENTRYPOINT [ "bokeh", "serve",  "--show", "economic/LookupTable/econ_viz.py", "--allow-websocket-origin=localhost:9098"]